# Generated by Django 3.1.7 on 2021-03-29 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0004_auto_20201104_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkt', models.CharField(max_length=30)),
                ('ilość', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('Produkty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.produkty')),
            ],
        ),
    ]
