# Generated by Django 3.1.7 on 2021-04-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0005_koszyk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koszyk',
            options={'verbose_name': 'Koszyk', 'verbose_name_plural': 'Koszyk'},
        ),
    ]
